using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmashDiscordRichPresence
{
    class Info
    {
        public static Dictionary<int, string> MODE_DESCRIPTIONS = new Dictionary<int, string>()
        {
            { 0x0, "In a Menu" },
            { 0x1, "In a Local Match" },
            { 0x3, "Playing Classic Mode" },
            { 0x4, "Playing Classic Mode With a Friend" },
            { 0x5, "Playing Master Orders" },
            { 0x6, "Playing Crazy Orders" },
            { 0x7, "Playing All-Star Mode" },
            { 0x8, "Playing All-Star Mode With a Friend" },
            { 0x9, "Playing Events Mode" },
            { 0xA, "Playing Events Mode With a Friend" },
            { 0xB, "Getting Good in Training Mode" },
            { 0xC, "Customizing Fighters" },
            { 0xD, "Customizing Mii Fighters" },
            { 0xE, "Digging Through the Vault" },
            { 0xF, "Changing Settings" },
            { 0x10, "Playing Angry Birds" },
            { 0x12, "Playing Homerun Contest" },
            { 0x13, "Playing Homerun Contest With a Friend" },
            { 0x14, "Playing Multiman Smash" },
            { 0x15, "Playing Multiman Smash With a Friend" },
            { 0x17, "Playing With a Friend Online" },
            { 0x18, "Playing With a Friend Online and Offline" },
            { 0x19, "Playing a For Glory Free for All" },
            { 0x1A, "Playing a For Glory Doubles Match" },
            { 0x1B, "Playing For Glory Doubles with a Friend" },
            { 0x1C, "Playing a For Glory 1v1 Match" },
            { 0x1D, "Playing a Free for All for Fun" },
            { 0x1E, "Playing a Doubles Match for Fun" },
            { 0x1F, "Playing Doubles With a Friend for Fun" },
            { 0x20, "Sharing a Screenshot" },
            { 0x21, "Sharing a Replay" },
            { 0x22, "Sharing a Mii" },
            { 0x23, "Sharing a Stage" },
            { 0x24, "Sending a Snapshot to a Friend" },
            { 0x25, "Sending a Replay to a Friend" },
            { 0x26, "Sending a Mii to a Friend" },
            { 0x27, "Sending a Stage to a Friend" },
            { 0x28, "Spectating a Match" },
            { 0x29, "Viewing Replays" },
            { 0x2A, "" },
            { 0x2C, "Checking Out Current Conquest" },
            { 0x2D, "Checking Out Conquest Results" },
            { 0x2E, "Building a Stage" },
            { 0x30, "Editing Amiibo" },
            { 0x31, "Playing Special Smash" },
            { 0x32, "Playing 8 Player Smash" },
            { 0x34, "Modifying the Rules" },
            { 0x39, "Playing Smash Tour" }
        };

        public static Dictionary<int, string> STAGE_NAMES = new Dictionary<int, string>()
        {
            { 0x00, "Battlefield" },
            { 0x2F, "Battlefield Omega" },
            { 0x6C, "Big Battlefield" },
            { 0x01, "Final Destination" },
            { 0x03, "Mushroom Kingdom U" },
            { 0x31, "Mushroom Kingdom U Omega" },
            { 0x02, "Mario Galaxy" },
            { 0x30, "Mario Galaxy Omega" },
            { 0x1E, "Delfino Plaza" },
            { 0x4C, "Delfino Plaza Omega" },
            { 0x04, "Mario Circuit" },
            { 0x32, "Mario Circuit Omega" },
            { 0x1F, "Mario Circuit(Brawl)" },
            { 0x4D, "Mario Circuit(Brawl) Omega" },
            { 0x2E, "Luigi's Mansion" },
            { 0x5C, "Luigi's Mansion Omega" },
            { 0x07, "Jungle Hijinx" },
            { 0x35, "Jungle Hijinx Omega" },
            { 0x22, "Kongo Jungle 64" },
            { 0x50, "Kongo Jungle 64 Omega" },
            { 0x06, "Skyloft" },
            { 0x34, "Skyloft Omega" },
            { 0x21, "Bridge of Eldin" },
            { 0x4F, "Bridge of Eldin Omega" },
            { 0x08, "Pyrosphere" },
            { 0x36, "Pyrosphere Omega" },
            { 0x23, "Norfair" },
            { 0x09, "Wolly World" },
            { 0x37, "Wolly World Omega" },
            { 0x24, "Yoshi's Island" },
            { 0x52, "Yoshi's Island Omega" },
            { 0x0A, "Great Cave Offensive" },
            { 0x38, "Great Cave Offensive Omega" },
            { 0x25, "Halberd" },
            { 0x53, "Halberd Omega" },
            { 0x0C, "Orbital Gate Assault" },
            { 0x3A, "Orbital Gate Assault Omega" },
            { 0x27, "Lylat Cruise" },
            { 0x55, "Lylat Cruise Omega" },
            { 0x05, "Kalos Pokemon League" },
            { 0x33, "Kalos Pokemon League Omega" },
            { 0x20, "Pokemon Stadium 2" },
            { 0x4E, "Pokemon Stadium 2 Omega" },
            { 0x2A, "Port Town Aero Drive" },
            { 0x58, "Port Town Aero Drive Omega" },
            { 0x0E, "Garden of Hope" },
            { 0x3C, "Garden of Hope Omega" },
            { 0x0D, "Coliseum" },
            { 0x3B, "Coliseum Omega" },
            { 0x28, "Castle Siege" },
            { 0x56, "Castle Siege Omega" },
            { 0x10, "Gamer" },
            { 0x3E, "Gamer Omega" },
            { 0x2B, "Onett" },
            { 0x59, "Onett Omega" },
            { 0x0B, "Town and City" },
            { 0x39, "Town and City Omega" },
            { 0x26, "Starterville" },
            { 0x54, "Starterville Omega" },
            { 0x0F, "Palutena's Temple" },
            { 0x3D, "Palutena's Temple Omega" },
            { 0x29, "Skyworld" },
            { 0x57, "Skyworld Omega" },
            { 0x16, "Wuhu Island" },
            { 0x44, "Wuhu Island Omega" },
            { 0x19, "Pilotwings" },
            { 0x47, "Pilotwings Omega" },
            { 0x18, "Wii Fit Studio" },
            { 0x46, "Wii Fit Studio Omega" },
            { 0x14, "Boxing Ring" },
            { 0x42, "Boxing Ring Omega" },
            { 0x15, "Boxing Ring" },
            { 0x43, "Boxing Ring Omega" },
            { 0x13, "Gaur Plain" },
            { 0x41, "Gaur Plain Omega" },
            { 0x2D, "Temple" },
            { 0x5B, "Temple Omega" },
            { 0x11, "Duck Hunt" },
            { 0x3F, "Duck Hunt Omega" },
            { 0x12, "Wrecking Crew" },
            { 0x40, "Wrecking Crew Omega" },
            { 0x2C, "75 M" },
            { 0x5A, "75 M Omega" },
            { 0x1D, "Flat Zone X" },
            { 0x4B, "Flat Zone X Omega" },
            { 0x1C, "Wily Castle" },
            { 0x4A, "Wily Castle Omega" },
            { 0x1B, "Wack-Land" },
            { 0x49, "Wack-Land Omega" },
            { 0x1A, "Windy Hill Zone" },
            { 0x48, "Windy Hill Zone Omega" },
            { 0x17, "Miiverse" },
            { 0x45, "Miiverse Omega" },
            { 0x70, "Dreamland 64" },
            { 0x71, "Dreamland 64 Omega" },
            { 0x6E, "Suzaku Castle" },
            { 0x6F, "Suzaku Castle Omega" },
            { 0x72, "Peach's Castle (64)" },
            { 0x73, "Peach's Castle (64) Omega" },
            { 0x74, "Hyrule Castle (64)" },
            { 0x75, "Hyrule Castle (64) Omega" },
            { 0x76, "Super Mario Maker" },
            { 0x77, "Super Mario Maker Omega" },
            { 0x78, "Pirate Ship" },
            { 0x79, "Pirate Ship Omega" },
            { 0x7C, "Midgar" },
            { 0x7D, "Midgar Omega" },
            { 0x7E, "Umbra Clock Tower" },
            { 0x7F, "Umbra Clock Tower Omega" },
            { 0x5D, "Multiman Smash Arena" },
            { 0x5E, "All-Star Resting Area" },
            { 0x5F, "Homerun Contest" },
            { 0x60, "Target Blast" },
            { 0x62, "Online Practice Stage" },
            { 0x63, "Equipment Testing Stage" },
            { 0x61, "Trophy Rush Stage" },
            { 0x68, "Trophy Pose BG 1" },
            { 0x69, "Trophy Pose BG 2" },
            { 0x6A, "Trophy Pose BG 3" },
            { 0x6B, "Trophy Pose BG 4" },
            { 0x65, "Trophy Award Platform" },
            { 0x66, "Trophy Hoard Platform" },
            { 0x6D, "Trophy Rush Stage 2P" }
        };

        public static Dictionary<int, string> CHARACTER_NAMES = new Dictionary<int, string>()
        {
            { 0x00, "Mii Fighter" },
            { 0x01, "Mii Swordsman" },
            { 0x02, "Mii Gunner" },
            { 0x04, "Mario" },
            { 0x0C, "Luigi" },
            { 0x0F, "Peach" },
            { 0x10, "Bowser" },
            { 0x08, "Yoshi" },
            { 0x25, "Rosalina and Luma" },
            { 0x2C, "Bowser Jr." },
            { 0x17, "Wario" },
            { 0x05, "Donkey Kong" },
            { 0x1C, "Diddy Kong" },
            { 0x14, "Mr. Game & Watch" },
            { 0x27, "Little Mac" },
            { 0x06, "Link" },
            { 0x11, "Zelda" },
            { 0x12, "Sheik" },
            { 0x15, "Ganondorf" },
            { 0x21, "Toon Link" },
            { 0x07, "Samus" },
            { 0x1A, "Zero Suit Samus" },
            { 0x19, "Pit" },
            { 0x29, "Palutena" },
            { 0x13, "Marth" },
            { 0x1E, "Ike" },
            { 0x2A, "Robin" },
            { 0x2B, "Duck Hunt" },
            { 0x09, "Kirby" },
            { 0x1D, "King Dedede" },
            { 0x18, "Meta Knight" },
            { 0x0A, "Fox" },
            { 0x16, "Falco" },
            { 0x0B, "Pikachu" },
            { 0x22, "Charizard" },
            { 0x1F, "Lucario" },
            { 0x2E, "Jigglypuff" },
            { 0x31, "Greninja" },
            { 0x20, "R.O.B." },
            { 0x0E, "Ness" },
            { 0x0D, "Captain Falcon" },
            { 0x28, "Villager" },
            { 0x1B, "Olimar" },
            { 0x26, "Wii Fit Trainer" },
            { 0x2D, "Shulk" },
            { 0x24, "Dr. Mario" },
            { 0x30, "Dark Pit" },
            { 0x2F, "Lucina" },
            { 0x32, "PAC-MAN" },
            { 0x33, "Mega Man" },
            { 0x23, "Sonic" },
            { 0x34, "Mewtwo" },
            { 0x36, "Lucas" },
            { 0x37, "Roy" },
            { 0x35, "Ryu" },
            { 0x38, "Cloud" },
            { 0x3A, "Corrin" },
            { 0x39, "Bayonetta" }
        };

        public static Dictionary<int, string> STAGE_IMAGE_KEYS = new Dictionary<int, string>()
        {
            { 0, "battlefield_f" },
            { 47, "battlefield_f" },
            { 108, "battlefield_f" },
            { 1, "end_f" },
            { 3, "mariou" },
            { 49, "mariou" },
            { 2, "galaxy" },
            { 48, "galaxy" },
            { 30, "xdolpic" },
            { 76, "xdolpic" },
            { 4, "mariokart" },
            { 50, "mariokart" },
            { 31, "xkart" },
            { 77, "xkart" },
            { 46, "xmansion" },
            { 92, "xmansion" },
            { 7, "dkreturns" },
            { 53, "dkreturns" },
            { 34, "64jungle" },
            { 80, "64jungle" },
            { 6, "skyward" },
            { 52, "skyward" },
            { 33, "xoldin" },
            { 79, "xoldin" },
            { 45, "temple" },
            { 91, "temple" },
            { 8, "metroid" },
            { 54, "metroid" },
            { 35, "xnorfair" },
            { 81, "xnorfair" },
            { 42, "xfzero" },
            { 88, "xfzero" },
            { 9, "yoshiu" },
            { 55, "yoshiu" },
            { 36, "dxyorster" },
            { 82, "dxyorster" },
            { 10, "cave" },
            { 56, "cave" },
            { 37, "xhalberd" },
            { 83, "xhalberd" },
            { 12, "assault" },
            { 58, "assault" },
            { 39, "xstarfox" },
            { 85, "xstarfox" },
            { 5, "kalos" },
            { 51, "kalos" },
            { 32, "xstadium" },
            { 78, "xstadium" },
            { 43, "dxonett" },
            { 89, "dxonett" },
            { 13, "colloseum_f" },
            { 59, "colloseum_f" },
            { 40, "xemblem" },
            { 86, "xemblem" },
            { 29, "gw3" },
            { 75, "gw3" },
            { 15, "angeland" },
            { 61, "angeland" },
            { 41, "xpalutena" },
            { 87, "xpalutena" },
            { 16, "gamer" },
            { 62, "gamer" },
            { 14, "pikminu" },
            { 60, "pikminu" },
            { 11, "village2" },
            { 57, "village2" },
            { 38, "xvillage" },
            { 84, "xvillage" },
            { 24, "wiifit" },
            { 70, "wiifit" },
            { 20, "punchout" },
            { 66, "punchout" },
            { 19, "xenoblade" },
            { 65, "xenoblade" },
            { 17, "duckhunt" },
            { 63, "duckhunt" },
            { 44, "xdonkey" },
            { 90, "xdonkey" },
            { 18, "wrecking" },
            { 64, "wrecking" },
            { 25, "pilotwings" },
            { 71, "pilotwings" },
            { 22, "wufu" },
            { 68, "wufu" },
            { 26, "windyhill" },
            { 72, "windyhill" },
            { 28, "wily" },
            { 74, "wily" },
            { 27, "pacland" },
            { 73, "pacland" },
            { 112, "pupupuland64_f" },
            { 113, "pupupuland64_f" },
            { 110, "streetfighter_f" },
            { 111, "streetfighter_f" },
            { 23, "miiverse" },
            { 69, "miiverse" },
            { 114, "peachcastle64_f" },
            { 115, "peachcastle64_f" },
            { 116, "hyrule64_f" },
            { 117, "hyrule64_f" },
            { 118, "mariomaker_f" },
            { 119, "mariomaker_f" },
            { 120, "xpirates_f" },
            { 121, "xpirates_f" },
            { 124, "midgar_f" },
            { 125, "midgar_f" },
            { 126, "umbra_f" },
            { 127, "umbra_f" }
        };

        public static List<int> SINGLEPLAYER_MODES = new List<int>()
        {
            0x3, 0x5, 0x6, 0x7, 0x9, 0xB, 0x10, 0x12, 0x14
        };

        public static List<int> ONE_V_ONE_MODES = new List<int>()
        {
            0x4, 0x8, 0xA, 0x13, 0x15, 0x17, 0x1C
        };

        public static List<int> IN_GAME_MODES = new List<int>()
        {
            0x1, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xA, 0xB, 0xC, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x31, 0x32
        };
    }
}

